/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import testpackageerror.FormVaksin;
import Controller.ArsipController;
import Controller.PesertaController;
import Controller.VaksinController;
import Model.Arsip;
//import testpackageerror.VaksinController;
import Model.Peserta;
import Model.Vaksin;
//import testpackageerror.Vaksin;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnInput = new javax.swing.JButton();
        btnJnsVak = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnData = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("ARSIP DATA");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 230, 62));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("INPUT DATA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 230, 62));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("JENIS VAKSIN");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 300, 62));

        btnExit.setBackground(new java.awt.Color(204, 204, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logout.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 130, 120));

        btnInput.setBackground(new java.awt.Color(204, 204, 255));
        btnInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/input.png"))); // NOI18N
        btnInput.setBorder(null);
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        jPanel2.add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 120));

        btnJnsVak.setBackground(new java.awt.Color(204, 204, 255));
        btnJnsVak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/syringe (1).png"))); // NOI18N
        btnJnsVak.setBorder(null);
        btnJnsVak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJnsVakActionPerformed(evt);
            }
        });
        jPanel2.add(btnJnsVak, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, 121));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        jLabel9.setText("Selamat Datang Admin !");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 40, -1, -1));

        btnData.setBackground(new java.awt.Color(204, 204, 255));
        btnData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/filetest.png"))); // NOI18N
        btnData.setBorder(null);
        btnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActionPerformed(evt);
            }
        });
        jPanel2.add(btnData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("LOG OUT");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 190, 62));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 850, 750));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 48)); // NOI18N
        jLabel1.setText("Mari Sukseskan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 53, -1, 52));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 48)); // NOI18N
        jLabel2.setText("VAKSINASI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 114, -1, -1));

        jLabel7.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Covid-19");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 181, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/diagnosis.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 256, -1, 406));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed

        dispose();
        
        Peserta data = new Peserta();
        FormInput frm = new FormInput();
        PesertaController ctrl = new PesertaController(data,frm);
        
        ctrl.KosongFormPeserta();
        ctrl.TampilDataPeserta();
        frm.setVisible(true);
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnJnsVakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJnsVakActionPerformed
        dispose();
        
        Vaksin datavak = new Vaksin();
        FormVak frmvak = new FormVak();
        VaksinController ctrlv = new VaksinController(datavak,frmvak);
        
        ctrlv.TampilDataVaksin();
        frmvak.setVisible(true);
    }//GEN-LAST:event_btnJnsVakActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        JOptionPane.showMessageDialog(null,"Logout Berhasil !");
        new FormLogin().show();
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Arsip datar = new Arsip();
        FormArsip frmar = new FormArsip();
        ArsipController ctrlar = new ArsipController(datar,frmar);
        
        ctrlar.KosongFormArsip();
        ctrlar.TampilDataArsip();
        frmar.setVisible(true);
    }//GEN-LAST:event_btnDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnData;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnInput;
    public javax.swing.JButton btnJnsVak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
